### ISSUE TITLE
Best Practices Question

### ISSUE THREAD

**Issue by AaronCoquet-Easypark** [DataEngineersNZ/dbt-snowflake-datops-materilizations#7]
Hi!
I just came across this repo, and want to use it. However, I want to make sure that I do things the dbt-thonic way. How would you suggest referencing a UDF in a model, to keep dbt aware of the lineage of it?

I can think of a couple of ways:
* Use a `-- depends on: ref('...')` flag in the header of any model that uses it
* Wrap it in a macro, and put the `-- depends on: ref('...')` flag in the header of the macro
  * This begs the question: Why not just turn the UDF into a macro?

Do you have any advice regarding this?

**Comment by jonhopper-dataengineers** [comment]
@AaronCoquet-Easypark example uses of a  UDF are:

- External Functions
- Adding testability to models which don't have references to other models such as a date dimension

When referencing the udf, we use the 'ref' macro passing in the e.g.

```
SELECT {{ ref('your_udf') }}(param1, param2) AS result
```

We have developed a [utilities project](https://github.com/DataEngineersNZ/dbt-snowflake-datops-utils) which contains macros called `depends_on_ref` and `depends_on_source` which takes into account if you are generating generating the docs or running dbt. 

With some of our materizations such as `stored procedures` or `tasks`, you need to break the dbt lineage so you can get the flow looking correct in the dag. However you need to ensure you remove a couple of files in the target folder before running the docs or run command otherwise dbt complains about lineage

We have developed a DataOps Framework (https://www.dataengineers.co.nz/solutions/dataops-framework/) for our clients which brings all components together and a set of python scripts which scaffolds all of the models and object types for you and reverse engineers some of the snowflake components into dbt models or updates yml definitions based on what has been deployed into snowflake. So in essense turning the dbt project into a full data engineering tool which can take advantage of doing things in a snowflake native way instead of just analytics using models.

[Feel free to drop us a message if you would like to know more](mailto:jon@dataengineers.co.nz)
